HandmadeFinal/Areas/Handmade/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HandmadeFinal.DAL;
using HandmadeFinal.Extention;
using HandmadeFinal.Models;
using HandmadeFinal.Utilities;
using HandmadeFinal.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace HandmadeFinal.Areas.Handmade.Controllers
{
    [Area("Handmade")]
    public class ProductAdminController : Controller
    {
        private AppDbContext _context;
        private IHostingEnvironment _env;

        public ProductAdminController(AppDbContext context,IHostingEnvironment env)
        {
            _context = context;
            _env = env;

        }
        public IActionResult Index()
        {
            return View(_context.Products.Include(p=>p.Category).Include(p=>p.ProductImages));
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return NotFound();
            Product product = await _context.Products.Include(p=>p.ProductImages).Include(p=>p.Category).FirstOrDefaultAsync(p=>p.Id==id);
            if (product == null) return NotFound();

            return View(product);
        }
       
        public async Task< IActionResult >AddItem()
        {
            ViewBag.Category = await _context.Categories.ToListAsync();
           

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItem(Product product,ProductImage productImage)
        {
            if (ModelState["Name"].ValidationState == ModelValidationState.Invalid ||
         ModelState["Description"].ValidationState == ModelValidationState.Invalid ||
         ModelState["Count"].ValidationState == ModelValidationState.Invalid ||
         ModelState["Price"].ValidationState == ModelValidationState.Invalid ||
         ModelState["Text"].ValidationState == ModelValidationState.Invalid
         )
            {
                return View();
            }
            Product products = new Product()
            {

                Name = product.Name,
                Text = product.Text,
                Description = product.Description,
                Price = product.Price,
                Count = product.Count,


            };
            await _context.SaveChangesAsync();

            var productid = _context.Products.LastOrDefault();


            foreach (var item in productImage.Photo)
            {
                if (!item.IsPhoto())
                {
                    ModelState.AddModelError("Photo", "Secdiginiz fayl sekil formatinda deyil!!! Zehmet Olmasa Sekil secin");
                    return View();
                }

                if (!item.PhotoSize(1))
                {
                    ModelState.AddModelError("Photo", "Sekilin olcusu 1 mb dan az olmalidir");
                    return View();

                }

                string FileName = await item.CopyPhoto(_env.WebRootPath, "category");
                productImage.Image = FileName;
           

                
                
                await _context.ProductImages.AddRangeAsync(new ProductImage
                {
                    ProductId=productid.Id,
                    Image=productImage.Image

                });
                await _context.SaveChangesAsync();

            }

           
            return RedirectToAction(nameof(Index));
            // return Content("Create Olundu");


        }

        public async Task<IActionResult>Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
       Product proDb = await _context.Products.Include(p => p.ProductImages).Include(p => p.Category).FirstOrDefaultAsync(p => p.Id == id);
            if (proDb == null) NotFound();
            ProductsView productsView = new ProductsView
            {
                Product= proDb,
                Categories = _context.Categories,
                ProductImages=_context.ProductImages.Where(p=>p.ProductId==id)


            };

            return View(productsView);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Product product, ProductImage productImage)
        {
            if (id == null) NotFound();

            Product proDb = await _context.Products.Include(p => p.ProductImages).Include(p => p.Category).FirstOrDefaultAsync(p => p.Id == id);
            if (proDb == null) NotFound();
            if (ModelState.IsValid)
            {
                return View(proDb);
            }
            if (productImage.UpdatePhoto != null)
            {
                foreach (var item in productImage.UpdatePhoto)
                {
                    if (!item.IsPhoto())
                    {
                        ModelState.AddModelError("Photo", "Secdiginiz fayl sekil formatinda deyil!!! Zehmet Olmasa Sekil secin");
                        return View();
                    }

                    if (!item.PhotoSize(1))
                    {
                        ModelState.AddModelError("Photo", "Sekilin olcusu 1 mb dan az olmalidir");
                        return View();

                    }
                    string FileName = await item.CopyPhoto(_env.WebRootPath, "category");
                    Utility.DeleteImage(_env.WebRootPath, productImage.Image);

                    productImage.Image = FileName;

                }



            }
            proDb.Name = product.Name;
            proDb.Text = product.Text;
            proDb.Description = product.Description;
            proDb.Price = product.Price;
            proDb.Count = product.Count;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }


        public async Task<IActionResult>Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Product proDb = await _context.Products.Include(p => p.ProductImages).Include(p => p.Category).FirstOrDefaultAsync(p => p.Id == id);
            if (proDb == null) NotFound();
            ProductsView productsView = new ProductsView
            {
                Product = proDb,
                Categories = _context.Categories,
                ProductImages = _context.ProductImages.Where(p => p.ProductId == id)


            };

            return View(productsView);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteProduct(int? id)
        {
            if (id == null) NotFound();
            Product product = await _context.Products.Include(p => p.ProductImages).Include(p => p.Category).FirstOrDefaultAsync(p => p.Id == id);
            if (product == null) NotFound();
            ProductImage productImage = await _context.ProductImages.FirstOrDefaultAsync(p => p.ProductId == id);
            if(productImage != null)
            {
                Utility.DeleteImage(_env.WebRootPath, productImage.Image);
                _context.Products.Remove(product);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

HandmadeFinal/Areas/Handmade/Views/ProductAdmin/AddItem.cshtml
@model Product
@{
    ViewData["Title"] = "AddItem";
}

<div class="container-fluid" style="margin-top:100px;">
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="@Model.Name"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Description"></label>
                <input asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Text"></label>
                <input asp-for="@Model.Text" class="form-control" />
                <span asp-validation-for="@Model.Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Count"></label>
                <input asp-for="@Model.Count" class="form-control" />
                <span asp-validation-for="@Model.Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Price"></label>
                <input asp-for="@Model.Price" class="form-control" />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>
            <div class="form-group" style="width:200px">
                <label asp-for="Category">Please Select Category</label>
                <select asp-for="@Model.CategoryId" data-size="7" data-style="btn btn-primary">
                    @foreach (var item in ViewBag.Category)
                    {
                        <option value="@item.Id">@item.CategoryName</option>
                    }
                </select>
            </div>


            <div class="form-group">
                <label asp-for="@Model.ProductImages.FirstOrDefault().Photo">Photo:</label>
                <input asp-for="@Model.ProductImages.FirstOrDefault().Photo" class="form-control" type="file" multiple name="Photo" accept="image/*" />
                <span asp-validation-for="@Model.ProductImages.FirstOrDefault().Photo" class="text-danger"></span>

            </div>
            <button type="submit" class="au-btn au-btn-icon au-btn--green au-btn--small">
                <i class="zmdi zmdi-plus"></i>Create
            </button>
        </form>
    </div>
</div>
</div>

HandmadeFinal/Areas/Handmade/Views/ProductAdmin/Delete.cshtml
@model ProductsView
@{
    ViewData["Title"] = "Delete";
}
<div class="container-fluid" style="margin-top:90px;">
    <div class="row">
        <div class="col-12">
            <span class="text-info">Name:</span>
            <h4>@Model.Product.Name</h4>
            <span class="text-info">Description:</span>
            <h4>@Model.Product.Description</h4>
            <span class="text-info">Text:</span>
            <h4>@Model.Product.Text</h4>
            <span class="text-info">Price:</span>
            <h4>@Model.Product.Price</h4>
            <span class="text-info">Count:</span>
            <h4>@Model.Product.Count</h4>
            <span class="text-info">Category:</span>
            <h4>@Model.Product.Category.CategoryName</h4>


            <span class="text-info">Image:</span>
            @foreach (var item in Model.ProductImages.Where(p => p.ProductId == p.Product.Id))
            {
                <img src="~/img/category/@item.Image" style="width:200px" />
            }


            <p class="text-danger">Are you sure delete this data?</p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post">
                <input type="submit" class="btn btn-danger" value="Delete" />
            </form>

        </div>
    </div>
    <div class="row">

        <div class="col-12 mt-3">
            <a asp-action="Index">Go Back</a>
        </div>
    </div>
</div>

HandmadeFinal/Areas/Handmade/Views/ProductAdmin/Detail.cshtml
@model Product
@{
    ViewData["Title"] = "Detail";
}

    <div class="container-fluid" style="margin-top:90px;">
        <div class="row">
            <div class="col-12">
                <h5>Name</h5>
                <p>@Model.Name</p>
                <h5>Description</h5>
                <p>@Model.Description</p>
                <h5>Text</h5>
                <p>@Model.Text</p>
                <h5>Count</h5>
                <p>@Model.Count</p>
                <h5>Price</h5>
                <p>@Model.Price</p>
                <h5>Category</h5>
                <p>@Model.Category.CategoryName</p>
                <h5>Image</h5>
                <img src="~/img/category/@Model.ProductImages.FirstOrDefault()?.Image" width="300px" />
            </div>
        </div>
        <div class="row">

            <div class="col-12">
                <a asp-action="Index">Go Back</a>
            </div>
        </div>
    </div>

HandmadeFinal/Areas/Handmade/Views/ProductAdmin/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
    
}

<div class="row " style="margin-top:90px;overflow-x:scroll;overflow-y:scroll;">
    <div class="col-md-12 ">
        <div class="table-data__tool">

            <div class="table-data__tool-left">
                <button class="au-btn au-btn-icon au-btn--green au-btn--small">
                    <i class="zmdi zmdi-plus"></i>  <a style="color:white;" href="ProductAdmin/AddItem">add item</a>
                </button>

                </div>
            </div>
        </div>
        <div class="table-responsive table-responsive-data2">
            <table class="table table-data2">
                <thead>
                    <tr>
                        <th scope="col"># </th>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Text</th>
                        <th scope="col">Count</th>
                        <th scope="col">Price</th>
                        <th scope="col">Category</th>
                        <th scope="col">Images</th>




                    </tr>
                </thead>
                <tbody>
                    @{int count = 1; }
                    @foreach (var item in Model)
                    {
                    <tr>

                        <td> @count</td>
                        <td>@item.Name</td>
                        
                         <td>@item.Text</td>

                        <td>@item.Count</td>

                        <td>@item.Price</td>
                        <td><img src="~/img/@item.ProductImages.FirstOrDefault()?.Image" alt="Alternate Text" style="width:150px;margin-top:20px;" /></td>
                        <td>@item.Category.CategoryName</td>
                        <td>
                            <div class="table-data-feature">
                                <button class="item" data-toggle="tooltip" data-placement="top" title="Send">
                                    <i class="zmdi zmdi-mail-send"></i>
                                </button>
                                <a asp-controller="ProductAdmin" asp-action="Update" asp-route-id="@item.Id" class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                    <i class="zmdi zmdi-edit"></i>
                                </a>
                                <a asp-controller="ProductAdmin" asp-action="Delete" asp-route-id="@item.Id" class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                    <i class="zmdi zmdi-delete"></i>
                                </a>
                                <a asp-controller="ProductAdmin" asp-action="Detail" asp-route-id="@item.Id" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                    <i class="zmdi zmdi-more"></i>
                                </a>
                            
                            </div>
                        </td>
                    </tr>
                        count++;
                        <tr class="spacer"></tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

HandmadeFinal/Areas/Handmade/Views/ProductAdmin/Update.cshtml
@model ProductsView
@{
    ViewData["Title"] = "Update";
}

    <div class="container-fluid" style="margin-top:90px;">
        <div class="row">
            <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label>Title:</label>
                        <input asp-for="@Model.Product.Name" class="form-control" />
                        <span asp-validation-for="@Model.Product.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Description:</label>
                        <input asp-for="@Model.Product.Description" class="form-control" />
                        <span asp-validation-for="@Model.Product.Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Count:</label>
                        <input asp-for="@Model.Product.Count" class="form-control" />
                        <span asp-validation-for="@Model.Product.Count" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Price:</label>
                        <input asp-for="@Model.Product.Price" class="form-control" />
                        <span asp-validation-for="@Model.Product.Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Text:</label>
                        <input asp-for="@Model.Product.Text" class="form-control" />
                        <span asp-validation-for="@Model.Product.Text" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Category</label>
                        <select class="form-control select2" name="CategoryId">
                            @foreach (var category in Model.Categories)
                            {
                                <option value="@category.Id">@category.CategoryName</option>
                            }


                        </select>
                    </div>
                    
                    <div class="form-group">
                        <label>Photo:</label>
                        @foreach (var item in Model.ProductImages)
                        {
                            <img src="~/img/category/@item.Image" width="200px" />

                            <input asp-for="@item.UpdatePhoto" class="form-control" accept="image\*" />
                            <span asp-validation-for="@item.UpdatePhoto" class="text-danger"></span>
                        }

                    </div>
                    <input type="submit" class="btn btn-primary" value="Update" />
                </form>
            </div>
        </div>
    </div>